tier1_cidr: 10.9.8.0/24
tier1_subnet: 10.9.8.0
tier1_subnet_mask: 255.255.255.0
tier1_broadcast: 10.9.8.255
tier1_gateway_server: 10.9.8.1 
tier1_dns_server: 10.9.8.10
tier1_domain_name: rockyhowto.lab

bare_metal:
  - node: tor01
    hostname: tor01
    mac: c8:9e:43:9c:4e:a2
    ip: 10.9.8.5
  - node: edg01
    hostname: edg01
    mac: a0:48:1c:93:e7:24
    ip: 10.9.8.1  
  - node: svc01
    hostname: svc01
    mac: a0:48:1c:89:ef:2b
    ip: 10.9.8.10
  - node: node01
    hostname: node01
    mac: 1c:fd:08:73:bb:7c
    ip: 10.9.8.110
  - node: node02
    hostname: node02
    mac: 1c:fd:08:72:46:1e
    ip: 10.9.8.120
  - node: node03
    hostname: node03
    mac: 1c:fd:08:73:bd:ea
    ip: 10.9.8.130
  - node: node04
    hostname: node04
    mac: 1c:fd:08:73:bb:e6
    ip: 10.9.8.140

### for role dhcpv2 ###

dhcpd_service_name: dhcpd
dhcpd_packages: dhcp-server


dhcpd_default_lease_time: 600
dhcpd_max_lease_time: 7200
dhcpd_subnet_range_start: 10.9.8.200
dhcpd_subnet_range_end: 10.9.8.250

dhcpd_filename: pxelinux.0
dhcpd_next_server: 10.9.8.10


### for role repo_server ###
local_repos:
  - file: local_baseos
    name: local_baseos
    description: Local RockyLinux BaseOS
    baseurl: file:///home/repo/baseos
  - file: local_appstream
    name: local_appstream
    description: Local RockyLinux Appstream
    baseurl: file:///home/repo/appstream
  - file: local_epel
    name: local_epel
    description: Local RockyLinux EPEL
    baseurl: file:///home/repo/epel
  - file: local_docker-ce-stable
    name: local_docker-ce-stable
    description: Docker CE Stable
    baseurl: file:///home/repo/docker-ce-stable
  - file: local_kubernetes
    name: local_kubernetes
    description: Local Kubernetes
    baseurl: file:///home/repo/kubernetes
  - file: local_wazuh
    name: local_wazuh
    description: Local Wazuh
    baseurl: file:///home/repo/wazuh
