---
# tasks file for dhcpd

#- name: Install dhcpd software
#  ansible.builtin.package:
#    name: "{{ dhcpd_packages }}"
#    state: present

- name: Display all variables/facts known for a host
  debug:
    var: hostvars[inventory_hostname]
  tags: debug_info

- name: Use template (dhcpd.conf.j2) to make /etc/dhcp/dhcpd.conf
  ansible.builtin.template:
    src: dhcpd.conf.j2
    dest: /tmp/dhcpd.conf
    backup: true
    mode: "0640"

#- name: Start and enable software
#  ansible.builtin.service:
#    name: "{{ dhcpd_service }}"
#    state: restarted
#    enabled: true
