- name: Make/Update /etc/chrony.conf
  lineinfile:
    dest: /etc/chrony.conf
    line: "allow 10.9.8.0/24"

- name: Restart service chrony
  ansible.builtin.service:
    name: chronyd
    state: restarted
    enabled: true
