local_repos:
  - file: local_baseos
    name: local_baseos
    description: Local RockyLinux BaseOS
    baseurl: file:///home/repo/baseos
  - file: local_appstream
    name: local_appstream
    description: Local RockyLinux Appstream
    baseurl: file:///home/repo/appstream
  - file: local_epel
    name: local_epel
    description: Local RockyLinux EPEL
    baseurl: file:///home/repo/epel
  - file: local_docker-ce-stable
    name: local_docker-ce-stable
    description: Docker CE Stable
    baseurl: file:///home/repo/docker-ce-stable
  - file: local_kubernetes
    name: local_kubernetes
    description: Local Kubernetes
    baseurl: file:///home/repo/kubernetes
  - file: local_wazuh
    name: local_wazuh
    description: Local Wazuh
    baseurl: file:///home/repo/wazuh
