- hosts:
    - services
    
  tasks:
  
  - name: Install tftp service
    dnf:
      name:
        - tftp-server
        - syslinux
        - syslinux-tftpboot
        - policycoreutils-python-utils 
      state: latest

  - name: Create new dirs
    ansible.builtin.file:
      path: "{{ item }}"
      state: directory
    loop:
      - /home/iso/mnt
      - /home/tftpboot
      - /home/tftpboot/rocky9pxe
      - /home/tftpboot/rocky9iso
      - /home/tftpboot/rocky9ks
      - /home/tftpboot/pxelinux.cfg
      
  - name: Update SElinux to allow tftp service to use the new dir
    command: 
    - semanage fcontext -a -t tftpdir_rw_t "/home/tftpboot(/.*)?"
    - restorecon -R -v /home/tftpboot

  - name: Edit the service to use the new dir
    lineinfile: 
      path: /lib/systemd/system/tftp.service 
      regexp: '^(.*)ExecStart(.*)$' 
      line: 'ExecStart=/usr/sbin/in.tftpd -s /home/tftpboot'
      backrefs: yes

  - name: Restart service tftp also issue daemon-reload to pick up config changes
    ansible.builtin.systemd_service:
      state: restarted
      daemon_reload: true
      name: tftp

- name: Extract kernel and ramdisk from a LiveCD
  community.general.iso_extract:
    image: /home/iso/Rocky9.iso
    dest: /home/tftpboot/rocky9pxe
    files:
    - images/pxeboot/initrd.img
    - images/pxeboot/initrd.img

  - name: copy contents to iso directorys
    shell: |
      mount -o loop /home/iso/Rocky9.iso /home/iso/mnt
      cp -rpv /home/iso/mnt/* /home/tftpboot/rocky9iso
      cp -rpv /usr/share/syslinux/* /home/tftpboot
















