- name: Install packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
  - freeipa-server
  - ipa-server-dns
  - freeipa-client

- name: Modify resolve to use new local IPA DNS server
  lineinfile:
    dest: /etc/resolv.conf
    line: "{{ item }}"
  with_items:
  - "search lan rockyhowto.lab"
  - "nameserver 10.9.8.10"

- name: Run freeIPA configuration script
  ignore_errors: true
  shell: |
    ipa-server-install -v \
      --unattended \
      --domain=rockyhowto.lab \
      --hostname svc01.rockyhowto.lab \
      --ip-address=10.9.8.10 \
      --realm ROCKYHOWTO.LAB \
      --ds-password ChangePassword \
      --admin-password ChangePassword \
      --setup-dns \
      --auto-reverse \
      --forwarder=8.8.8.8 \
      --ntp-pool=north-america.pool.ntp.org

- name: Run kinit
  ignore_errors: true
  shell: echo 'ChangePassword' | kinit admin

- name: Setup dns zone
  ignore_errors: true
  shell: ipa dnszone-mod --allow-transfer=10.9.8.0/24 rockyhowto.lab

- name: Setup NFS share for user home directories
  ignore_errors: true
  shell: |
    systemctl enable --now nfs-server rpcbind
    mkdir /home/domainusers
    echo '/home/domainusers 10.9.8.0/24(rw,sync,no_subtree_check,root_squash)' >> /etc/exports
    exportfs -rav
    ipa service-add nfs/svc01.rockyhowto.lab
    kadmin.local ktadd nfs/svc01.rockyhowto.lab
    systemctl restart nfs-server
    ipa config-mod --homedirectory=/home/domainusers --defaultshell=/bin/bash

- name: Setup sudoers group and permissions
  ignore_errors: true
  shell: |
    ipa group-add --desc='local administrators' sudoers
    ipa sudorule-add sudoers_sudo \
      --hostcat=all \
      --runasusercat=all \
      --runasgroupcat=all \
      --cmdcat=all
    ipa sudorule-add-user sudoers_sudo --group sudoers
    ipa sudorule-add-option sudoers_sudo --sudooption='!authenticate'
    authselect enable-feature with-sudo
    systemctl restart sssd

- name: Setup ansible user to work with freeIPA
  ignore_errors: true
  shell: |
    ipa user-add ansible --first=Ansible --last=Automation --random
    mkdir -m0750 -p /home/domainusers/ansible/.ssh
    ssh-keygen \
      -C ansible@rockyhowto.lab \
      -f /home/domainusers/ansible/.ssh/id_rsa \
      -q -N ""
    chown -hRv ansible:ansible /home/domainusers/ansible
    ipa user-mod ansible --sshpubkey="$(cat /home/domainusers/ansible/.ssh/id_rsa.pub)"
    ipa group-add-member sudoers --users=ansible

- name: Modify resolve to use new local IPA DNS server
  lineinfile:
    dest: /etc/resolv.conf
    line: "{{ item }}"
  with_items:
  - "search lan rockyhowto.lab"
  - "nameserver 10.9.8.10"


- name: Add Repo directory rule to httpd
  blockinfile:
    path: /etc/httpd/conf.d/repo.conf
    create: yes
    block: |
      Alias /repo/ /home/repo/
        <Directory /home/repo/>
          Options Indexes FollowSymLinks
          AllowOverride None
          Require all granted
        </Directory>

- name: Update new repo dir in SElinux
  ignore_errors: true
  shell: |
    semanage fcontext -a -t public_content_t "/home/repo(/.*)?"
    restorecon -F -R -v /home/repo

- name: Add PXE directory rule to httpd
  blockinfile:
    path: /etc/httpd/conf.d/pxe.conf
    create: yes
    block: |
      Alias /tftpboot/ /home/tftpboot/
        <Directory /home/tftpboot/>
          Options Indexes FollowSymLinks
          AllowOverride None
          Require all granted
        </Directory>

- name: Update new tftp dir in SElinux
  ignore_errors: true
  shell: |
    semanage fcontext -a -t public_content_t "/home/tftpboot(/.*)?"
    restorecon -F -R -v /home/tftpboot

