---
#- name: Install createrepo RPM
#  package:
#   name: createrepo
#    state: present

#- name: Install yum-utils RPM
#  package:
#    name: yum-utils
#    state: present

#- name: Delete default repos
#  ignore_errors: true
#  shell: /bin/rm -rf /etc/yum.repos.d/*

- name: Use template (repo.temp.j2) to make /tmp/repo.temp
  ansible.builtin.template:
    src: repo.temp.j2
    dest: "{{ repo_tmp_path_file }}"
    backup: true
    mode: "0666"

- name: Create repo directories
  ansible.builtin.file:
    path: /home/repo/{{ item.repo }}
    state: directory
  loop: "{{ sync_repos }}"

- name: Create repo directories and populate form the internet
  ignore_errors: true
  shell: |
        dnf reposync \
       --download-path=/home/repo/ \
        --repoid={{ item.repo}} \
        --newest-only \
        --download-metadata \
        --config={{ repo.tmp.path.file }} ;
  loop: "{{ sync_repos }}"
      
#- name: Build up local repo conf
#  yum_repository:
#    file: "{{ item.file }}"
#    name: "{{ item.name }}"
#    description: "{{ item.description }}"
#    baseurl: "{{ item.baseurl }}"
#    gpgcheck: False
#  loop: "{{ local_repos }}"

# - name: Delete rocky repos
#   ignore_errors: true
#   shell: /bin/rm -rf /etc/yum.repos.d/rocky*

#- name: Update selinux
#  ignore_errors: true
#  shell: restorecon -r /home/repo
