---

- name: Install required dhcpd packages
  ansible.builtin.package:
    name: "{{ dhcpd_packages }}"
    state: present

- name: Use template (dhcpd.conf.j2) to make /etc/dhcp/dhcpd.conf
  ansible.builtin.template:
    src: dhcpd.conf.j2
    dest: /etc/dhcp/dhcpd.conf
    backup: true
    mode: "0640"

- name: Restart service dhcpd
  ansible.builtin.service:
    name: dhcpd
    state: restarted
    enabled: true
